INSERT INTO baseType VALUES('DOCUMENT_DNI','TYPE_DOCUMENT','DNI','',null);
INSERT INTO baseType VALUES('DOCUMENT_LE','TYPE_DOCUMENT','LE','',null);
INSERT INTO baseType VALUES('DOCUMENT_PAST','TYPE_DOCUMENT','Pasaporte','',null);
INSERT INTO baseType VALUES('DOCUMENT_C_EXTRA','TYPE_DOCUMENT','Carne de extrangeria','',null);

INSERT INTO baseType VALUES('PERSON_ACT','STATUS_PERSON','Activo','',null);
INSERT INTO baseType VALUES('PERSON_INACT','STATUS_PERSON','Inactivo','',null);

INSERT INTO baseType VALUES('USER_ACT','STATUS_USER','Activo','',null);
INSERT INTO baseType VALUES('USER_INACT','STATUS_USER','Inactivo','',null);

