INSERT INTO baseType VALUES('PRODUCT_BASAR','TYPE_PRODUCT','Basar','',NULL);
INSERT INTO baseType VALUES('PRODUCT_ROOM','TYPE_PRODUCT','Habitacion','',NULL);
INSERT INTO baseType VALUES('PRODUCT_BAR','TYPE_PRODUCT','Bar','',NULL);
INSERT INTO baseType VALUES('PRODUCT_OTHER','TYPE_PRODUCT','Otros','',NULL);

INSERT INTO baseType VALUES('HOTEL_ACT','STATUS_HOTEL','Activo','',NULL);
INSERT INTO baseType VALUES('HOTEL_INACT','STATUS_HOTEL','Inactivo','',NULL);

INSERT INTO baseType VALUES('ROLE_ACT','STATUS_ROLE','Activo','',NULL);
INSERT INTO baseType VALUES('ROLE_INACT','STATUS_ROLE','Inactivo','',NULL);

